import { Person } from "./src/Person.js";
import { Contact } from "./src/Contact.js";
import { Plot, PersonLog } from "./src/Plot.js";
let a = new Person("A");
let b = new Person("B");
let c = new Person("C");
const persons=[a,b,c];
let plot = new Plot(new Date("2020-10-27"));
plot.addContact(new Contact(a, b, { intensity: 0.7, date: new Date("2020-10-30") }));
plot.addContact(new Contact(a, c, { intensity: 0.7, date: new Date("2020-11-3") }));
plot.addContact(new Contact(c, b, { intensity: 0.7, date: new Date("2020-11-4") }));
const log=plot.log;
console.log(log);
import {visualize} from "./src/graphics.js";
visualize(plot);